CATALOGUE_HOST: catalogue-{{env}}.daws2025.online
USER_HOST: user-{{env}}.daws2025.online
CART_HOST: cart-{{env}}.daws2025.online
SHIPPING_HOST: shipping-{{env}}.daws2025.online
PAYMENT_HOST: payment-{{env}}.daws2025.online